#!perl -wT
use strict;
use Test::More;

# we enable all Perl warnings, but we don't "use warnings 'all'" because 
# we want to disable the warnings generated by Sys::Syslog
#no warnings;
#use warnings qw(closure deprecated exiting glob io misc numeric once overflow
#                pack portable recursion redefine regexp severe signal substr
#                syntax taint uninitialized unpack untie utf8 void);
use warnings;

# any remaining warning should be severly punished
eval "use Test::NoWarnings";
my $tests = $@ ? 0 : 1;
plan tests => $tests;

# ----------
# CPAN-RT#25488: disconnect_log() produced a "uninitialized" warnings
# because $current_proto was used without being checked.
# 
use Sys::Syslog  qw(:standard :macros);
openlog("sys-syslog-test", "", LOG_USER);
closelog();
